language: python

python:
  - "2.7"

addons:
  firefox: "39.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirments.txt

script: nosetests  -v --processes=10 --process-timeout=12
